#!/bin/bash
in=${!##\\input } # ${!#} is the last argument
out="${in%.in}.out"
case "$1" in
	zsh) ;;
	*) exit 1 ;;
esac

:>completion.log

mapfile -t <"$in"
./zsh.sh -p 'pdfjam ' -s '_pdfjam' -d completion.log "${MAPFILE[@]}" >"$out"
