return {
	'# Change operation mode',
	{'help', short = 'h', flag = '=', help = 'Print help message.'},
	{'version', short = 'V', flag = '=', help = 'Print the version number.'},
	{'configpath', flag = '=', help = 'Print the `configpath` variable.'},
	{'quiet', short = 'q', help = 'Suppress verbose commentary on progress.'},
	{'batch', help = 'Run pdfjam sequentially on each input file in turn, and produce a separate output file for each input.'},
	{'checkfiles', flag = '+', help = 'Use `file` utility to determine file type.'},
	{'vanilla', help = 'Suppress the reading of any pdfjam configuration files.'},
	{'enc', description = 'encoding', completer = '_enc', help = 'Command-line encoding as understood by `iconv`.'},
	'# Define where to put files',
	{'outfile', alias = 'output', short = 'o', flag = '=', description = 'output', completer = '_output', help = 'File or directory name for output(s).'},
	{'suffix', argtype = 'string', help = 'Suffix for output, when file name is not given explicitly.'},
	{'tidy', flag = '+', exclude = {"builddir"}, help = 'Clean temporary build directory.'},
	{'builddir', exclude = {"tidy", "no-tidy"}, description = 'directory', completer = '_files -/', help = 'Set build directory.'},
	'# Configure LaTeX run',
	{'latex', description = 'engine', completer = '_absolute_command_paths', help = 'Absolute path to LaTeX engine to be used.'},
	{'latexopts', flag = '*', description = 'latex command line options', completer = ' ', help = 'Provide arguments to use when calling the LaTeX engine.'},
	{'preamble', flag = '*', argtype = 'tex', help = 'Append code to the LaTeX preamble.'},
	{'runs', argtype = 'num', argnames = {'number of runs'}, help = 'Run latex N times, for each output document made.'},
	'# Set PDF metadata',
	{'keepinfo', flag = '+', help = 'Preserve Title, Author, Subject and Keywords (from the last input PDF) in the output PDF file.'},
	{'pdftitle', argtype = 'string', help = 'Set Title of the output PDF file.'},
	{'pdfauthor', argtype = 'string', help = 'Set Author of the output PDF file.'},
	{'pdfsubject', argtype = 'string', help = 'Set Subject of the output PDF file.'},
	{'pdfkeywords', argtype = 'string', help = 'Set Keywords of the output PDF file.'},
	{[0] = '# Set paper format',
		{'paper', description = 'paper name', completer = '($paperformats)', quote = '"', help = 'Paper format.', example = '--paper letter a4.pdf 1-2'},
		{'papersize', argtype = 'dims-comma', argnames = {'width', 'height'}, help = 'Specify a paper size as WIDTH,HEIGHT.', example = '--papersize 15cm,30cm a4.pdf 1-2'},
		"$paperflags",
	},
	'# Adjust page',
	{'landscape', flag = '+', help = 'Exchange width and height of paper.', example = '--landscape square.pdf 1'},
	{'twoside', flag = '+', help = 'Specify `twoside` document class option.', example = "--twoside --offset '1cm 0' a4.pdf 1-2"},
	{'otheredge', flag = '+', help = 'Rotate every odd page by 180 degrees.', example = '--otheredge a4.pdf 1-2'},
	{'pagecolor', description = 'rgb', completer = '_pagecolor', help = 'Background color.', example = '--pagecolor 255,255,0 a4text.pdf 1'},
	'# Pdfpages settings',
	'## N-up pages',
	{'nup', description = 'XxY', completer = '_nup', help = 'Put multiple logical pages onto each sheet of paper.', example = '--nup 2x3 a4.pdf 1-9'},
	{'column', argtype = 'bool', help = 'Use column-major layout, where successive pages are arranged in columns down the paper.', example = '--column true --nup 4x2 --landscape a4.pdf 1-11'},
	{'columnstrict', argtype = 'bool', help = 'For column-major layout only: Do not balance the columns on the last page.', example = '--columnstrict true --column true --nup 2x3 a4.pdf 1-10'},
	'## Shift pages',
	{'delta', argtype = 'dims-space', argnames = {'horizontal space', 'vertical space'}, help = 'Put some horizontal and vertical space between the logical pages.', example = "--delta '3cm 1cm' --nup 2x2 a4.pdf 1-4"},
	{'offset', argtype = 'dims-space', argnames = {'horizontal displacement', 'vertical displacement'}, help = 'Displace the origin of the inserted pages.', example = "--offset '3cm 1cm' a4.pdf 1"},
	{'frame', argtype = 'bool', help = 'Put a frame around each logical page.', example = "--frame true --nup 2x2 --offset '2mm 3mm' a4.pdf 1-4"},
	'## Scale pages',
	{'noautoscale', argtype = 'bool', help = 'Suppress automatic scaling of pages.', example = '--noautoscale true square.pdf 1'},
	{'fitpaper', argtype = 'bool', help = 'Adjust the paper size to the size of the inserted document.', example = '--fitpaper true square.pdf 1'},
	{'turn', argtype = 'bool', help = 'Tell PDF viewer to display landscape pages in landscape orientation. On by default.'},
	{'pagetemplate', argtype = 'num', argnames = {'pagenumber'}, help = 'Declare page to be used as a template. All other pages are scaled such that they match within its size.', example = '--pagetemplate 2 --pages 1 a4.pdf a5.pdf'},
	{'templatesize', argtype = 'dims-comma', argnames = {'width', 'height'}, help = 'Specify size of page template. All pages are scaled such that they match within this size.', example = "--templatesize '50cm,10cm' --pages 1 a4.pdf a4landscape.pdf"},
	{'rotateoversize', argtype = 'bool', help = 'Rotate oversized pages.', example = '--rotateoversize true --pages 1 a4.pdf a4landscape.pdf'},
	'## Mirror pages',
	{'reflect', argtype = 'bool', help = 'Reflect output pages.', example = '--reflect true --nup 2x1 --landscape a4.pdf 1-2'},
	{'reflect*', argtype = 'bool', help = 'Reflect input pages.', example = '--reflect* true --nup 2x1 --landscape a4.pdf 1-2'},
	{[0] = '## Create signatures',
		{'signature', argtype = 'num4', help = 'Create booklets by rearranging pages into signatures of 2 pages each.', example = '--signature 4 --nup 2x1 --landscape a4.pdf 1-8'},
		{'signature*', argtype = 'num4', help = 'Similar to signature, but for right-edge binding.', example = '--signature* 4 --nup 2x1 --landscape a4.pdf 1-8'},
		{'booklet', argtype = 'bool', help = 'Same as signature with signature size chosen such that all pages fit into one signature.', example = '--booklet true --nup 2x1 --landscape a4.pdf 1-8'},
		{'booklet*', argtype = 'bool', help = 'Similar to booklet, but for right-edge binding.', example = '--booklet* true --nup 2x1 --landscape a4.pdf 1-8'},
	},
	{'flip-other-edge', argtype = 'bool', help = 'For signatures/booklets: set duplex binding edge perpendicular (instead of parallel) to signature binding edge. Has same result as `otheredge`.', example = '--flip-other-edge true --booklet true --nup 2x1 --landscape a4.pdf 1-4'},
	'## Add blank pages',
	{'openright', argtype = 'bool', help = 'Put an empty page before the first logical page.', example = '--openright true --nup 2x1 a4.pdf 1-3'},
	{'openrighteach', argtype = 'bool', help = 'Put an empty page before the first logical page of each file.', example = '--openrighteach true --nup 2x1 a4.pdf 1 a4text.pdf 1-3'},
	{[0] = '## Duplicate pages',
		{'doublepages', argtype = 'bool', help = 'Insert every page twice.', example = '--doublepages true --nup 2x1 a4.pdf 1-2'},
		{'doublepagestwist', argtype = 'bool', help = 'Insert every page twice: once upside down and once normally.', example = '--doublepagestwist true --nup 2x1 a4.pdf 1-2'},
		{'doublepagestwistodd', argtype = 'bool', help = 'Insert every page twice: once normally and once upside down.', example = '--doublepagestwistodd true --nup 2x1 a4.pdf 1-2'},
		{'doublepagestwist*', argtype = 'bool', help = 'Insert every page twice: for odd pages, the first copy is upside down; for even pages, the second copy.', example = '--doublepagestwist* true --nup 2x1 a4.pdf 1-2'},
		{'doublepagestwistodd*', argtype = 'bool', help = 'Insert every page twice: for odd pages, the second copy is upside down; for even pages, the first copy.', example = '--doublepagestwistodd* true --nup 2x1 a4.pdf 1-2'},
		{'duplicatepages', argtype = 'num', help = 'Insert every page NUM times.', example = '--duplicatepages 3 a4.pdf 1'},
	},
	'## Run LaTeX commands',
	{'pagecommand', argtype = 'tex', help = 'Declare LaTeX commands, which are executed on each sheet of paper.', example = "--pagecommand '\\section{Welcome to page \\thepage}\\thispagestyle{empty}' a4.pdf 1-2"},
	{'pagecommand*', argtype = 'tex', help = 'Declare LaTeX commands, which are executed on the very first page only.', example = "--pagecommand* '\\section{Some pretty number pages}' a4.pdf 1-2"},
	{'picturecommand', argtype = 'tex', help = 'Similar to pagecommand, but executed within a picture environment with base point at the lower left page corner.', example = "--picturecommand '\\put(72,72){Welcome to page \\thepage}' a4.pdf 1-2"},
	{'picturecommand*', argtype = 'tex', help = 'Similar to picturecommand, but for very first page only.', example = "--picturecommand* '\\put(72,72){Some pretty number pages' a4.pdf 1-2"},
	'## Add hyperlinks',
	{'link', argtype = 'bool', help = 'Each inserted page becomes the target of the hyperlink ⟨filename⟩.⟨pagenumber⟩.'},
	{'linkname', argtype = 'name', help = 'For link option only: Change the link base name from ⟨filname⟩ to NAME.'},
	{'threadname', argtype = 'name', help = 'For thread option only: Change the thread name from ⟨filename⟩ to NAME.'},
	{'linkfit', description = 'destination', completer = '(Fit|FitH ⟨top⟩|FitV ⟨left⟩|FitB|FitBH ⟨top⟩|FitBV ⟨left⟩|Region)', help = 'For link option only: Specify, how the viewer displays a linked page.'},
	{'addtotoc', description = 'pagenumber,section,level,heading,label', completer = '_addtotoc', help = 'Add an entry to the table of contents.'},
	{'addtolist', description = 'pagenumber,type,heading,label', completer = '_addtolist', help = 'Add an entry to the list of figures, the list of tables, or any other list.'},
	'# Graphicx options',
	{'viewport', argtype = 'dims-space', argnames = {'left', 'bottom', 'right', 'top'}, help = 'Consider image to consist of given rectangle only.', example = "--viewport '0 4cm 8cm 16cm' a4.pdf 1"},
	{'trim', argtype = 'dims-space', argnames = {'left', 'bottom', 'right', 'top'}, help = 'Similar to viewport, but here the four lengths specify the amount to remove or add to each side.', example = "--trim '0 4cm 8cm 16cm' a4.pdf 1"},
	{'angle', argtype = 'angle', help = 'Rotation angle (counterclockwise).', example = '--angle 45 a4.pdf 1'},
	{'origin', description = 'origin', completer = '(c l r b t bl br tl tr)', help = 'Origin for rotation.'},
	{'width', argtype = 'dim', argnames = {'width'}, help = 'Required width. The graphic is scaled to this width.', example = '--width 10cm a4.pdf 1'},
	{'height', argtype = 'dim', argnames = {'height'}, help = 'Required height. The graphic is scaled to this height.', example = '--height 10cm a4.pdf 1'},
	{'totalheight', argtype = 'dim', argnames = {'height'}, help = 'Required height+depth. Differs from height if rotation has occured.', example = '--totalheight 10cm --angle 45 a4.pdf 1'},
	{'keepaspectratio', argtype = 'bool', help = 'Do not distort figure if both width and height are given.', example = '--keepaspectratio true --width 10cm --height 10cm a4.pdf 1'},
	{'scale', description = 'float', completer = ' ', help = 'Scale factor.', example = '--scale 2 a4.pdf 1'},
	{'clip', argtype = 'bool', help = 'Clip the graphic to the viewport.', example = "--clip true --viewport '0 4cm 8cm 16cm' a4.pdf 1"},
	{'pagebox', description = 'bounding box', completer = '(mediabox cropbox bleedbox trimbox artbox)', help = 'Specify which PDF bounding box specification to read.'},
	{'draft', argtype = 'bool', help = 'Switch to draft mode.', example = '--draft true a4.pdf 1'},
}
